version: '3'

services:
    http-server:
      build: nginx-custom
      volumes:
        - ${install_path}/${project_name}:/var/application/${project_name}
        - ./nginx-custom/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - worker

    worker:
      build: php-fpm-custom
      working_dir: /var/application/${project_name}
      volumes:
        - ${install_path}/${project_name}:/var/application/${project_name}
        - ./php-fpm-custom/php.ini:/usr/local/etc/php/php.ini
      links:
        - db

    db:
      image: mariadb:10.1
      env_file:
        - ./mariadb-custom/setup.env
